apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskvine-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskvine-gateway.labels" . | nindent 4 }}
spec:
  selector:
    app: taskvine-gateway
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
